apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myakscluster-77a7"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myakscluster-77a7"
  template:
    metadata:
      labels:
        app: "myakscluster-77a7"
    spec:
      containers:
        - name: "myakscluster-77a7"
          image: "kalana.azurecr.io/myakscluster"
          ports:
          - containerPort: 5000