on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: kalana.azurecr.io
        username: ${{ secrets.acr_kalana_username }}
        password: ${{ secrets.acr_kalana_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t kalana.azurecr.io/myakscluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push kalana.azurecr.io/myakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myakscluster83f1 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myakscluster83f1`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myakscluster83f1
        container-registry-url: kalana.azurecr.io
        container-registry-username: ${{ secrets.acr_kalana_username }}
        container-registry-password: ${{ secrets.acr_kalana_password }}
        secret-name: myaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myakscluster83f1
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          kalana.azurecr.io/myakscluster:${{ github.sha }}
        imagepullsecrets: |
          myaksclusterdockerauth
